modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPL 3.0"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
